import "./globals.css"
import { Inter } from "next/font/google"
import { startValidatorUpdateInterval, validatorUpdate } from "@/utils/database"

const inter = Inter({ subsets: ["latin"] })
export const metadata = {
  title: "NexusDatabase",
  description: "Generated by NexusDatabase",
}

export default async function RootLayout({ children }) {
  await startValidatorUpdateInterval()
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
