import "./globals.css"
import { Inter } from "next/font/google"
import {
  startValidatorUpdateInterval,
  validatorUpdate,
  checkForValidatorSubgraphUpdates,
  BlockInsert,
} from "@/utils/database"

import { getBlocks, getNodeOperators, getValidators } from "@/utils/apiCalls"
const inter = Inter({ subsets: ["latin"] })
export const metadata = {
  title: "NexusDatabase",
  description: "Generated by NexusDatabase",
}

export default async function RootLayout({ children }) {
  await startValidatorUpdateInterval()
  await BlockInsert()

  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
